## Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [4]:
import numpy as np 
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question - 2
Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [7]:
l1=[]
l2=[]
for i in range(5):
    x=input("l1-enter 5 elements: ")   # taking inputs from user
    l1.append(x)
for i in range(5):
    x=input("l2-enter 5 elements: ") # taking inputs from user
    l2.append(x)
arr1=np.array(l1) 
arr2=np.array(l2)
arr=np.concatenate((arr1,arr2)) # concatenate
print(arr)
arr_sort=np.sort(arr)#sorting
print(arr_sort)

['1' '2' '3' '4' '5' '6' '3' '1' '3' '5']
['1' '1' '2' '3' '3' '3' '4' '5' '5' '6']


## Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [14]:
arr=np.array([[1,2,3],[4,5,6]])
dim=arr.ndim
size=arr.size
print("dimension:",dim)
print("size :",size)


dimension: 2
size : 6


## Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [20]:
arr = np.arange(5)
print("Shape :",arr.shape)
arr1=arr[np.newaxis,:]
print("\nShape of arr1: ",arr1.shape)
arr2=arr[:,np.newaxis]
print("\nShape of arr2: ",arr2.shape)




Shape : (5,)

Shape of arr1:  (1, 5)

Shape of arr2:  (5, 1)


In [ ]:
## Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [27]:
arr1 = np.square([1,2,3,4,5])
arr2 = np.square([6,7,8,9,10])
arr_vs=np.vstack((arr1,arr2))
print("vertical stack :",arr_vs)
arr_hs=np.hstack((arr1,arr2))
print("\nHorizontal stack: ",arr_hs)

vertical stack : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]

Horizontal stack:  [  1   4   9  16  25  36  49  64  81 100]


## Questions 6:
How to get unique items and counts of unique items?

In [46]:
arr=np.array([1,3,2,5,2,7,5,2,5,2335,1336,1,73,4,7,0])
#arr_unqitems=np.unique(arr)
arr_unqitems,arr_count_unqitems = np.unique(arr,return_counts=True)
#print(arr_unqitems)
arr_f=np.array((arr_unqitems,arr_count_unqitems)).T
print(arr_f)

[[   0    1]
 [   1    2]
 [   2    3]
 [   3    1]
 [   4    1]
 [   5    3]
 [   7    2]
 [  73    1]
 [1336    1]
 [2335    1]]
